import type { Issue } from "./issue";
import type { Requirement } from "./requirement";
import type { HealthLevel, ReleaseGateResult, RiskRecord } from "./risk";
import type { VersionFilterLevel } from "./version";

export type VersionSummary = {
  scopeLevel: VersionFilterLevel;
  version: string;
  versionLabel: string;
  versionLine: string;
  versionLineKey: string;
  releaseVersion: string;
  cycleVersion: string;
  patchVersion: string;
  releaseKey: string;
  cycleKey: string;
  versionKey: string;
  versionScene: string;
  majorVersion: string;
  majorVersionKey: string;
  minorIteration: string;
  fullVersion: string;
  requirements: Requirement[];
  issues: Issue[];
  risks: RiskRecord[];
  totalRequirements: number;
  completedRequirements: number;
  inProgressRequirements: number;
  riskRequirementCount: number;
  requirementProgress: number;
  onlineRequirements: number;
  totalIssues: number;
  openIssues: number;
  riskIssueCount: number;
  highRiskCount: number;
  mediumRiskCount: number;
  lowRiskCount: number;
  stageDistribution: Record<string, number>;
  stageBucketDistribution: Record<string, number>;
  issueStatusDistribution: Record<string, number>;
  severityDistribution: Record<string, number>;
  ownersTop: { name: string; count: number }[];
  riskOwnersTop: { name: string; count: number }[];
  issueOwnersTop: { name: string; count: number }[];
  laggingRequirementCount: number;
  cleanupBlockedCount: number;
  cleanupBoundCount: number;
  openHighSeverityCount: number;
  missingCriticalStageDatesCount: number;
  preStageRequirementCount: number;
  legacyIssueCount: number;
  legacyHighRiskIssueCount: number;
  topRisks: RiskRecord[];
  healthScore: number;
  healthLevel: HealthLevel;
  releaseGate: ReleaseGateResult;
};
